branch-defaults:
  default:
    environment: sinv-udacity-dev9
    group_suffix: null
environment-defaults:
  sinv-udacity-dev:
    branch: null
    repository: null
deploy:
    artifact: ./www/Archive.zip
global:
  application_name: sinv-udacity
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Node.js 18 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application